# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Printf
version:      0.06
version_from: Printf.pm
installdirs:  site
requires:
    Exception::Class:              1.21
    Readonly:                      1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
