---
name: Text-Printf
version: 0.07
author:
  - Eric Roode <roode@cpan.org>
abstract: 'A simple, lightweight text fill-in class.'
license: perl
requires:
  Exception::Class: 1.21
  Readonly: 1.00
provides: {}
generated_by: Module::Build version 0.2611
