---
name: Text-Printf
version: 1.00
author:
  - 'Eric J. Roode <roode@cpan.org>'
abstract: 'A simple, lightweight text fill-in class.'
license: unrestricted
build_requires:
  Exception::Class: 1.21
  Readonly: 1.00
  Test::More: 0.10
provides:
  Text::Printf:
    file: lib/Text/Printf.pm
    version: 1.00
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
